### PR TITLE
Fix Hash/Array fingerprint instability across JRuby versions

### LINKED ISSUE #78: Fix `Hash#inspect` format dependency in fingerprint input
- 3 test failures (all ECS modes) when `concatenate_sources` + UTF-8 fields contain nested Hashes
  - **Root cause:** In `lib/logstash/filters/fingerprint.rb`, line 168:
    ```ruby
    to_string << "|#{k}|#{deep_sort_hashes(event.get(k))}".force_encoding("UTF-8")
    ```
    String interpolation calls `.to_s` → `.inspect` on Hashes/Arrays. JRuby 10 changed `Hash#inspect` from `{key=>"val"}` to `{key => "val"}` (spaces around `=>`), producing different bytes → different SHA1 digest.
  - **Fix options:**
    1. **(Preferred)** Make `deep_sort_hashes` return a canonical string representation independent of `Hash#inspect` — e.g., recursive pipe-delimited format
    2. Update test expected values (fragile — breaks again on next Ruby formatting change)
  - **Note:** This is a **behavioral change for users** — existing fingerprints in production will change on upgrade regardless of fix approach. Needs consideration.

### PR DESCRIPTION
**Pull request by donoghuc**
JRuby 10 changed Hash#inspect spacing, producing different fingerprint bytes for nested Hash/Array fields. Use a  pipe-delimited format instead of relying on Hash#inspect.

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

Closes: https://github.com/logstash-plugins/logstash-filter-fingerprint/issues/78

### CODE REVIEW

**Comment by donoghuc** [comment]
> Note: This is a behavioral change for users — existing fingerprints in production will change on upgrade regardless of fix approach. Needs consideration.

In practice this would only appply to complex ruby objects. I would imagine in practice most of the actual use case are for string values. While this change *will* change the sha for some complex objects, that "duplication" risk is one off. Trying to keep full behavior compatability would inevitably produce a messy and brittle solution that is likely not worth it.

File: lib/logstash/filters/fingerprint.rb [hunk 1]
```diff
@@ -201,6 +201,20 @@ def deep_sort_hashes(object)
...
+  # For Hashes and Arrays, produces a pipe-delimited format that is
+  # independent of Hash#inspect formatting (which changed in JRuby 10).
+  def to_canonical_string(object)
+    case object
+    when Hash
+      object.sort.map { |k, v| "#{to_canonical_string(k)}|#{to_canonical_string(v)}" }.join("|")
+    when Array
+      object.map { |e| to_canonical_string(e) }.join("|")
+    else
+      object
```
Comment (andsel) [inline lib/logstash/filters/fingerprint.rb:216]: Shouldn't return a string in case of Object?

```suggestion
      object.to_s
```

**Review by andsel — CHANGES_REQUESTED** [review]
The general idea sounds good, I've left a doubt.

File: lib/logstash/filters/fingerprint.rb (hunk 1 above)
Comment (donoghuc) [reply lib/logstash/filters/fingerprint.rb:216]: My fault for the confusing name. We actually dont want to always produce a string (for example the hash of an integer `1` would be different than the string `"1"`. I updated the helper name to avoid the inconsistency, but we dont want the `.to_s` here.

**Review by andsel — APPROVED** [review]
LGTM
