### PR TITLE
make openssl digest objects thread local

### LINKED ISSUE #46: Using Ruby Execution, MD5 and no key throws exception in pipelineworker
For all general issues, please provide the following details for fast resolution:

- Version: master but also 6.4.2
- Operating System: OS X
- Config File (if you have sensitive info, please remove it): `input { generator { count => 100 } } filter { fingerprint { } } output {}`
- Sample Data:
- Steps to Reproduce:
```
$ ~/src/logstash/bin/logstash -e 'input { generator { count => 100 } } filter { fingerprint { } } output {}' --log.level=debug
Sending Logstash logs to /Users/simlu/src/logstash/logs which is now configured via log4j2.properties
[2018-10-30T20:19:30,338][DEBUG][logstash.modules.scaffold] Found module {:module_name=>"netflow", :directory=>"/Users/simlu/src/logstash/modules/netflow/configuration"}
[2018-10-30T20:19:30,346][DEBUG][logstash.plugins.registry] Adding plugin to the registry {:name=>"netflow", :type=>:modules, :class=>#<LogStash::Modules::Scaffold:0x1567e07 @directory="/Users/simlu/src/logstash/modules/netflow/configuration", @module_name="netflow", @kibana_version_parts=["6", "0", "0"]>}
[2018-10-30T20:19:30,349][DEBUG][logstash.modules.scaffold] Found module {:module_name=>"fb_apache", :directory=>"/Users/simlu/src/logstash/modules/fb_apache/configuration"}
[2018-10-30T20:19:30,351][DEBUG][logstash.plugins.registry] Adding plugin to the registry {:name=>"fb_apache", :type=>:modules, :class=>#<LogStash::Modules::Scaffold:0x65129082 @directory="/Users/simlu/src/logstash/modules/fb_apache/configuration", @module_name="fb_apache", @kibana_version_parts=["6", "0", "0"]>}
[2018-10-30T20:19:30,508][DEBUG][logstash.runner          ] -------- Logstash Settings (* means modified) ---------
[2018-10-30T20:19:30,508][DEBUG][logstash.runner          ] node.name: "kaka.it.su.se"
[2018-10-30T20:19:30,508][DEBUG][logstash.runner          ] path.data: "/Users/simlu/src/logstash/data"
[2018-10-30T20:19:30,509][DEBUG][logstash.runner          ] *config.string: "input { generator { count => 100 } } filter { fingerprint { } } output {}"
[2018-10-30T20:19:30,509][DEBUG][logstash.runner          ] modules.cli: []
[2018-10-30T20:19:30,509][DEBUG][logstash.runner          ] modules: []
[2018-10-30T20:19:30,509][DEBUG][logstash.runner          ] modules_list: []
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] modules_variable_list: []
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] modules_setup: false
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] config.test_and_exit: false
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] config.reload.automatic: false
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] config.reload.interval: 3000000000
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] config.support_escapes: false
[2018-10-30T20:19:30,510][DEBUG][logstash.runner          ] config.field_reference.parser: "STRICT"
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] metric.collect: true
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.id: "main"
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.system: false
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.workers: 4
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.output.workers: 1
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.batch.size: 125
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.batch.delay: 50
[2018-10-30T20:19:30,511][DEBUG][logstash.runner          ] pipeline.unsafe_shutdown: false
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] *pipeline.java_execution: false (default: true)
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] pipeline.reloadable: true
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] path.plugins: []
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] config.debug: false
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] *log.level: "debug" (default: "info")
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] version: false
[2018-10-30T20:19:30,512][DEBUG][logstash.runner          ] help: false
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] log.format: "plain"
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] http.host: "127.0.0.1"
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] http.port: 9600..9700
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] http.environment: "production"
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] queue.type: "memory"
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] queue.drain: false
[2018-10-30T20:19:30,513][DEBUG][logstash.runner          ] queue.page_capacity: 67108864
[2018-10-30T20:19:30,514][DEBUG][logstash.runner          ] queue.max_bytes: 1073741824
[2018-10-30T20:19:30,514][DEBUG][logstash.runner          ] queue.max_events: 0
[2018-10-30T20:19:30,514][DEBUG][logstash.runner          ] queue.checkpoint.acks: 1024
[2018-10-30T20:19:30,515][DEBUG][logstash.runner          ] queue.checkpoint.writes: 1024
[2018-10-30T20:19:30,515][DEBUG][logstash.runner          ] queue.checkpoint.interval: 1000
[2018-10-30T20:19:30,515][DEBUG][logstash.runner          ] dead_letter_queue.enable: false
[2018-10-30T20:19:30,517][DEBUG][logstash.runner          ] dead_letter_queue.max_bytes: 1073741824
[2018-10-30T20:19:30,517][DEBUG][logstash.runner          ] slowlog.threshold.warn: -1
[2018-10-30T20:19:30,517][DEBUG][logstash.runner          ] slowlog.threshold.info: -1
[2018-10-30T20:19:30,517][DEBUG][logstash.runner          ] slowlog.threshold.debug: -1
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] slowlog.threshold.trace: -1
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] keystore.classname: "org.logstash.secret.store.backend.JavaKeyStore"
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] keystore.file: "/Users/simlu/src/logstash/config/logstash.keystore"
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] path.queue: "/Users/simlu/src/logstash/data/queue"
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] path.dead_letter_queue: "/Users/simlu/src/logstash/data/dead_letter_queue"
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] path.settings: "/Users/simlu/src/logstash/config"
[2018-10-30T20:19:30,518][DEBUG][logstash.runner          ] path.logs: "/Users/simlu/src/logstash/logs"
[2018-10-30T20:19:30,521][DEBUG][logstash.runner          ] xpack.management.enabled: false
[2018-10-30T20:19:30,522][DEBUG][logstash.runner          ] xpack.management.logstash.poll_interval: 5000000000
[2018-10-30T20:19:30,522][DEBUG][logstash.runner          ] xpack.management.pipeline.id: ["main"]
[2018-10-30T20:19:30,522][DEBUG][logstash.runner          ] xpack.management.elasticsearch.username: "logstash_system"
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.management.elasticsearch.url: ["https://localhost:9200"]
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.management.elasticsearch.ssl.verification_mode: "certificate"
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.management.elasticsearch.sniffing: false
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.enabled: false
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.elasticsearch.url: ["http://localhost:9200"]
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.collection.interval: 10000000000
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.collection.timeout_interval: 600000000000
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.elasticsearch.username: "logstash_system"
[2018-10-30T20:19:30,523][DEBUG][logstash.runner          ] xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
[2018-10-30T20:19:30,524][DEBUG][logstash.runner          ] xpack.monitoring.elasticsearch.sniffing: false
[2018-10-30T20:19:30,524][DEBUG][logstash.runner          ] xpack.monitoring.collection.pipeline.details.enabled: true
[2018-10-30T20:19:30,524][DEBUG][logstash.runner          ] xpack.monitoring.collection.config.enabled: true
[2018-10-30T20:19:30,524][DEBUG][logstash.runner          ] node.uuid: ""
[2018-10-30T20:19:30,524][DEBUG][logstash.runner          ] --------------- Logstash Settings -------------------
[2018-10-30T20:19:30,590][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-10-30T20:19:30,676][DEBUG][logstash.agent           ] Setting up metric collection
[2018-10-30T20:19:30,772][DEBUG][logstash.instrument.periodicpoller.os] Starting {:polling_interval=>5, :polling_timeout=>120}
[2018-10-30T20:19:30,792][DEBUG][logstash.instrument.periodicpoller.cgroup] One or more required cgroup files or directories not found: /proc/self/cgroup, /sys/fs/cgroup/cpuacct, /sys/fs/cgroup/cpu
[2018-10-30T20:19:31,009][DEBUG][logstash.instrument.periodicpoller.jvm] Starting {:polling_interval=>5, :polling_timeout=>120}
[2018-10-30T20:19:31,200][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-10-30T20:19:31,209][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2018-10-30T20:19:31,240][DEBUG][logstash.instrument.periodicpoller.persistentqueue] Starting {:polling_interval=>5, :polling_timeout=>120}
[2018-10-30T20:19:31,257][DEBUG][logstash.instrument.periodicpoller.deadletterqueue] Starting {:polling_interval=>5, :polling_timeout=>120}
[2018-10-30T20:19:31,324][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.0.0-alpha1"}
[2018-10-30T20:19:31,345][DEBUG][logstash.agent           ] Starting agent
[2018-10-30T20:19:31,467][DEBUG][logstash.agent           ] Converging pipelines state {:actions_count=>1}
[2018-10-30T20:19:31,483][DEBUG][logstash.agent           ] Executing action {:action=>LogStash::PipelineAction::Create/pipeline_id:main}
[2018-10-30T20:19:32,868][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"generator", :type=>"input", :class=>LogStash::Inputs::Generator}
[2018-10-30T20:19:33,107][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"plain", :type=>"codec", :class=>LogStash::Codecs::Plain}
[2018-10-30T20:19:33,146][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@id = "plain_a524b19b-9847-4d4e-bf65-dd79435548d7"
[2018-10-30T20:19:33,147][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@enable_metric = true
[2018-10-30T20:19:33,148][DEBUG][logstash.codecs.plain    ] config LogStash::Codecs::Plain/@charset = "UTF-8"
[2018-10-30T20:19:33,168][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@count = 100
[2018-10-30T20:19:33,169][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@id = "82c2469d0b171910f7c93a3b855a500fa9b8d890b6c62482d5feb5295d112077"
[2018-10-30T20:19:33,170][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@enable_metric = true
[2018-10-30T20:19:33,186][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@codec = <LogStash::Codecs::Plain id=>"plain_a524b19b-9847-4d4e-bf65-dd79435548d7", enable_metric=>true, charset=>"UTF-8">
[2018-10-30T20:19:33,188][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@add_field = {}
[2018-10-30T20:19:33,189][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@threads = 1
[2018-10-30T20:19:33,189][DEBUG][logstash.inputs.generator] config LogStash::Inputs::Generator/@message = "Hello world!"
[2018-10-30T20:19:33,274][DEBUG][logstash.plugins.registry] On demand adding plugin to the registry {:name=>"fingerprint", :type=>"filter", :class=>LogStash::Filters::Fingerprint}
[2018-10-30T20:19:33,300][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@id = "636a8c3128cb1e46504a2c191f9de8e70b15796011ae9611b85e9d0ef66e07ae"
[2018-10-30T20:19:33,301][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@enable_metric = true
[2018-10-30T20:19:33,302][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@add_tag = []
[2018-10-30T20:19:33,306][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@remove_tag = []
[2018-10-30T20:19:33,307][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@add_field = {}
[2018-10-30T20:19:33,307][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@remove_field = []
[2018-10-30T20:19:33,307][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@periodic_flush = false
[2018-10-30T20:19:33,307][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@source = ["message"]
[2018-10-30T20:19:33,308][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@target = "fingerprint"
[2018-10-30T20:19:33,308][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@base64encode = false
[2018-10-30T20:19:33,308][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@method = "SHA1"
[2018-10-30T20:19:33,311][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@concatenate_sources = false
[2018-10-30T20:19:33,311][DEBUG][logstash.filters.fingerprint] config LogStash::Filters::Fingerprint/@concatenate_all_fields = false
[2018-10-30T20:19:33,386][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-10-30T20:19:33,640][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e run>"}
[2018-10-30T20:19:33,722][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2018-10-30T20:19:33,739][DEBUG][logstash.inputs.generator] Closing {:plugin=>"LogStash::Inputs::Generator"}
[2018-10-30T20:19:33,769][DEBUG][logstash.agent           ] Starting puma
[2018-10-30T20:19:33,790][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2018-10-30T20:19:33,845][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>2, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,845][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>4, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,845][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.689Z, "sequence"=>0, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,848][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>3, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,848][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>8, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,848][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>6, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>7, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>12, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>10, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>11, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>14, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>15, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,849][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>16, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>18, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>19, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>22, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>20, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>23, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,850][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>26, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>24, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>30, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>27, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>28, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>34, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,851][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>31, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>32, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>38, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>35, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>36, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>42, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>39, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,852][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>40, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>43, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>46, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>44, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>47, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>50, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>48, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,853][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>51, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>54, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>52, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>55, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>56, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>58, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,854][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>59, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>60, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>62, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>63, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>66, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>67, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>64, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,855][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>70, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>68, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>71, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,845][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.715Z, "sequence"=>1, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>76, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>74, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>72, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,856][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>78, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>75, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>80, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.716Z, "sequence"=>5, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>79, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>9, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,857][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>84, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>82, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>83, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.717Z, "sequence"=>13, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>86, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>88, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>87, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,858][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>17, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>92, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>90, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.728Z, "sequence"=>96, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>91, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>21, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,859][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>94, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,860][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>95, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,860][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.718Z, "sequence"=>25, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,860][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.728Z, "sequence"=>98, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,860][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.728Z, "sequence"=>99, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,860][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>29, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,861][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.719Z, "sequence"=>33, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,861][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.720Z, "sequence"=>37, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,861][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>41, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,862][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>45, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,862][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.721Z, "sequence"=>49, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,862][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.722Z, "sequence"=>53, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,863][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>57, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,863][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.723Z, "sequence"=>61, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,864][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>65, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,864][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.724Z, "sequence"=>69, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,865][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>73, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,865][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.725Z, "sequence"=>77, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,867][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>81, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,868][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.726Z, "sequence"=>85, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,868][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>89, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,871][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.727Z, "sequence"=>93, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,873][DEBUG][logstash.pipeline        ] filter received {"event"=>{"host"=>"kaka.it.su.se", "@timestamp"=>2018-10-30T19:19:33.728Z, "sequence"=>97, "message"=>"Hello world!", "@version"=>"1"}}
[2018-10-30T20:19:33,885][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e sleep>"}
[2018-10-30T20:19:33,888][DEBUG][logstash.pipeline        ] Shutting down filter/output workers {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e run>"}
[2018-10-30T20:19:33,966][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"4", "backtrace"=>["org.bouncycastle.crypto.digests.GeneralDigest.update(Unknown Source)", "org.bouncycastle.crypto.digests.GeneralDigest.finish(Unknown Source)", "org.bouncycastle.crypto.digests.SHA1Digest.doFinal(Unknown Source)", "org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineDigest(Unknown Source)", "java.security.MessageDigest.digest(MessageDigest.java:365)", "org.jruby.ext.openssl.Digest.finish(Digest.java:204)", "org.jruby.ext.openssl.Digest$INVOKER$i$0$0$finish.call(Digest$INVOKER$i$0$0$finish.gen)", "org.jruby.RubyClass.finvoke(RubyClass.java:557)", "org.jruby.runtime.Helpers.invoke(Helpers.java:399)", "org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:354)", "org.jruby.ext.digest.RubyDigest$DigestInstance.digest(RubyDigest.java:320)", "org.jruby.ext.digest.RubyDigest$DigestInstance.hexdigest(RubyDigest.java:339)", "Users.simlu.src.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$method$fingerprint_openssl$0(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:161)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)", "Users.simlu.src.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$block$filter$4(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:140)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "Users.simlu.src.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$method$filter$0(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:135)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:143)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:162)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:159)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb:320)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0$__VARARGS__(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb:286)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call(RubyProc.java:246)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)", "java.lang.Thread.run(Thread.java:748)"], :thread=>"#<Thread:0x4d00405e run>"}
[2018-10-30T20:19:33,967][DEBUG][logstash.pipeline        ] Setting shutdown {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e run>"}
[2018-10-30T20:19:33,972][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x33befff9 run>"}
[2018-10-30T20:19:33,977][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>1, "@timestamp"=>2018-10-30T19:19:33.715Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,977][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>5, "@timestamp"=>2018-10-30T19:19:33.716Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,978][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>9, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"073d4e1f5e47da4790308902d9db0916ce50c028", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,978][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>13, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"a88af7817ccbd87913843250be905af843207058", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,978][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>17, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,979][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>21, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"e2f1453b4d74b60b746acef8e370ca256d6bab62", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,979][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>25, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"41931c5d928bf1bdd46adbe446a52e4ec3d2e1f0", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,979][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>29, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"c99ecf5aa82981a981b55a3637c9afef7573c7c9", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,979][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>33, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"1de2bfe3db616f89c8e4447c37e96c9ef3076676", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,980][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>37, "@timestamp"=>2018-10-30T19:19:33.720Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"a88af7817ccbd87913843250676157b70379a924", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,980][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>41, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d46c1faf412ccea3b692dc712b6bc162f17223e7", "host"=>"kaka.it.su.se"}}
Exception in thread "Ruby-0-Thread-4: :1" [2018-10-30T20:19:33,980][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>4, "@timestamp"=>2018-10-30T19:19:33.716Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,982][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>8, "@timestamp"=>2018-10-30T19:19:33.716Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,982][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>12, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"38ef0869667b521d196925b324ca52ee3bae0040", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,982][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>16, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,983][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>20, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,983][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>24, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,984][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>0, "@timestamp"=>2018-10-30T19:19:33.689Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,980][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>45, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,984][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>28, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"92b404e556588ced6c1acd4ebf053f6809f73a93", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,984][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>32, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,985][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>36, "@timestamp"=>2018-10-30T19:19:33.720Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"0cb51f07b717b91cbc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,985][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>49, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,985][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>3, "@timestamp"=>2018-10-30T19:19:33.716Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,985][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>40, "@timestamp"=>2018-10-30T19:19:33.720Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,986][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>44, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,986][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>7, "@timestamp"=>2018-10-30T19:19:33.716Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"92b404e556588ced6c1acd4ebf053f6809f73a93", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,986][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>48, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"39928812bf2354d5274893d2c0f58b928cb83487", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,986][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>11, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"5d492555ee17d74c85830f9abc82653fd7013887", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,986][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>52, "@timestamp"=>2018-10-30T19:19:33.722Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>53, "@timestamp"=>2018-10-30T19:19:33.722Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>15, "@timestamp"=>2018-10-30T19:19:33.717Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>56, "@timestamp"=>2018-10-30T19:19:33.723Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"39928812bf2354d5274893d2c0f58b928cb83487", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>19, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>23, "@timestamp"=>2018-10-30T19:19:33.718Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"92b404e556588ced6c1acd4ebf053f6809f73a93", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>57, "@timestamp"=>2018-10-30T19:19:33.723Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>60, "@timestamp"=>2018-10-30T19:19:33.723Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>27, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,987][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>61, "@timestamp"=>2018-10-30T19:19:33.723Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>64, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"9577496e607f8628fbc6bd7f8e9dd944495e3174", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>31, "@timestamp"=>2018-10-30T19:19:33.719Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>68, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>65, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>35, "@timestamp"=>2018-10-30T19:19:33.720Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>69, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>72, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>39, "@timestamp"=>2018-10-30T19:19:33.720Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"daa5c735bff832018b27c5d5f7423656fac39a89", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>75, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"4fe8dc5103e88bccda29008eb9b053c098a1b29c", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,988][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>73, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>43, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>79, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>77, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>47, "@timestamp"=>2018-10-30T19:19:33.721Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>81, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>83, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"c2ee6aa42def45c626d4ec1c4a5cfe1797748a42", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,989][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>51, "@timestamp"=>2018-10-30T19:19:33.722Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"f0107ad545509040a7021d6965e78f86d9820feb", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>85, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>87, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
java.lang.ArrayIndexOutOfBoundsException: 4
        at org.bouncycastle.crypto.digests.GeneralDigest.update(Unknown Source)[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>89, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}

        at org.bouncycastle.crypto.digests.GeneralDigest.finish(Unknown Source)
        at org.boun[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>91, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>93, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>55, "@timestamp"=>2018-10-30T19:19:33.722Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>95, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>97, "@timestamp"=>2018-10-30T19:19:33.728Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
cycastle.crypto.digests.SHA1Digest.doFinal(Unknown Source)
[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>99, "@timestamp"=>2018-10-30T19:19:33.728Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
        at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineDigest(Unknown Source)[2018-10-30T20:19:33,990][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>59, "@timestamp"=>2018-10-30T19:19:33.723Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}

        at java.security.MessageDigest.digest(MessageDigest.java:365)
        at org.jruby.ext.openssl.Digest.finish(Digest.java:204)
        at org.jruby.ext.openssl.Digest$INVOKER$i$0$0$finish.call(Digest$INVOKER$i$0$0$finish.gen)
        at org.jruby.RubyClass.finvoke(RubyClass.java:557)
        at org.jruby.runtime.Helpers.invoke(Helpers.java:399)
        at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:354)
        at org.jruby.ext.digest.RubyDigest$DigestInstance.digest(RubyDigest.java:320)
        at org.jruby.ext.digest.RubyDigest$DigestInstance.hexdigest(RubyDigest.java:339)
        at Users.simlu.src.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$method$fingerprint_openssl$0(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:161)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
[2018-10-30T20:19:33,991][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>63, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"92b404e556588ced6c1acd4ebf053f6809f73a93", "host"=>"kaka.it.su.se"}}
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        at Users.simlu.src.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$block$filter$4(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:140)
[2018-10-30T20:19:33,991][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>67, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
        at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
        at org.jruby.runtime.Block.yield(Block.java:165)
        at org.jruby.RubyArray.each(RubyArray.java:1734)
        at Users.simlu.src.logstash.[2018-10-30T20:19:33,991][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>71, "@timestamp"=>2018-10-30T19:19:33.724Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_fingerprint_minus_3_dot_2_dot_0.lib.logstash.filters.fingerprint.RUBY$method$filter$0(/Users/simlu/src/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-fingerprint-3.2.0/lib/logstash/filters/fingerprint.rb:135)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:143)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:162)
        at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
        at org.jruby.runtime.Block.yield(Block.java:165)
        at org.jruby.RubyArray.each(RubyArray.java:1734)[2018-10-30T20:19:33,992][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>76, "@timestamp"=>2018-10-30T19:19:33.725Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}

        at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)
        at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/filters/base.rb:159)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)[2018-10-30T20:19:33,992][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>80, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"8420db3e2a1f728e3ed7c7eaef62f1f951e7be5c", "host"=>"kaka.it.su.se"}}

        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)[2018-10-30T20:19:33,992][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>84, "@timestamp"=>2018-10-30T19:19:33.726Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}

        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
        at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:289)
        at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)[2018-10-30T20:19:33,992][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>88, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}

        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb:320)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0$__VARARGS__(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
        at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
        at Users.simlu.src.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/Users/simlu/src/logstash/logstash-core/lib/logstash/pipeline.rb:286)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
[2018-10-30T20:19:33,993][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>92, "@timestamp"=>2018-10-30T19:19:33.727Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"bdc17224dddd504298badcfe10325476c3d2e1f0", "host"=>"kaka.it.su.se"}}
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:289)
        at org.jruby.RubyProc.call(RubyProc.java:246)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
        at java.lang.Thread.run(Thread.java:748)
[2018-10-30T20:19:33,993][DEBUG][logstash.pipeline        ] output received {"event"=>{"sequence"=>96, "@timestamp"=>2018-10-30T19:19:33.728Z, "@version"=>"1", "message"=>"Hello world!", "fingerprint"=>"d3486ae9136e7856bc42212385ea797094475802", "host"=>"kaka.it.su.se"}}
[2018-10-30T20:19:33,996][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x34f64716 run>"}
[2018-10-30T20:19:34,007][DEBUG][logstash.api.service     ] [api-service] start
[2018-10-30T20:19:34,016][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x58f94f9e dead>"}
[2018-10-30T20:19:34,016][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread {:pipeline_id=>"main", :thread=>"#<Thread:0x657db5f6 dead>"}
[2018-10-30T20:19:34,028][DEBUG][logstash.filters.fingerprint] Closing {:plugin=>"LogStash::Filters::Fingerprint"}
[2018-10-30T20:19:34,032][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e run>"}
[2018-10-30T20:19:34,240][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-10-30T20:19:34,317][DEBUG][logstash.instrument.periodicpoller.os] Stopping
[2018-10-30T20:19:34,341][DEBUG][logstash.instrument.periodicpoller.jvm] Stopping
[2018-10-30T20:19:34,344][DEBUG][logstash.instrument.periodicpoller.persistentqueue] Stopping
[2018-10-30T20:19:34,345][DEBUG][logstash.instrument.periodicpoller.deadletterqueue] Stopping
[2018-10-30T20:19:34,432][DEBUG][logstash.agent           ] Shutting down all pipelines {:pipelines_count=>1}
[2018-10-30T20:19:34,438][DEBUG][logstash.agent           ] Converging pipelines state {:actions_count=>1}
[2018-10-30T20:19:34,442][DEBUG][logstash.agent           ] Executing action {:action=>LogStash::PipelineAction::Stop/pipeline_id:main}
[2018-10-30T20:19:34,464][DEBUG][logstash.pipeline        ] Stopping inputs {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e dead>"}
[2018-10-30T20:19:34,470][DEBUG][logstash.inputs.generator] Stopping {:plugin=>"LogStash::Inputs::Generator"}
[2018-10-30T20:19:34,475][DEBUG][logstash.pipeline        ] Stopped inputs {:pipeline_id=>"main", :thread=>"#<Thread:0x4d00405e dead>"}
[2018-10-30T20:19:34,484][DEBUG][logstash.pipeline        ] Worker terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x33befff9 dead>"}
[2018-10-30T20:19:34,485][DEBUG][logstash.pipeline        ] Worker terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x34f64716 dead>"}
[2018-10-30T20:19:34,486][DEBUG][logstash.pipeline        ] Worker terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x58f94f9e dead>"}
[2018-10-30T20:19:34,489][DEBUG][logstash.pipeline        ] Worker terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x657db5f6 dead>"}
$
```

It actually doesn't happen every time so you might need to run it a few times.

Using Java execution doesn't throw this error.

### PR DESCRIPTION
**Pull request by jsvd**
easy way to reproduce issue: `bin/logstash -e 'input { generator { count => 10000 } } filter { fingerprint { } } output {}'`

fixes #46

### CODE REVIEW

**Comment by jsvd** [comment]
[work in progress] setting this to be thread local has the problem if the same thread uses two fingerprint plugins. This will happen in real life and also in the spec suite.

**Comment by jsvd** [comment]
fixed by using the plugin ID in the thread local variable name.

File: lib/logstash/filters/fingerprint.rb [hunk 1]
```diff
@@ -153,19 +152,22 @@ def fingerprint_ipv4_network(ip_string)
   end
 
   def fingerprint_openssl(data)
+    digest_string = "digest-#{id}"
+    Thread.current[digest_string] ||= select_digest(@method)
```
Comment (colinsurprenant) [inline lib/logstash/filters/fingerprint.rb]: 👍

Comment (colinsurprenant) [reply lib/logstash/filters/fingerprint.rb]: I suggest adding a comment about the use of the threadlocal var here, the intent is not self-explanatory; re OpenSSL::Digest::____ objects (jruby openssl) are not thread safe.

**Comment by colinsurprenant** [comment]
LGTM - just a minor note about commenting the threadlocal intent. 
Nice works!
